name: ecorota_bus
description: Aplicativo EcoRota Bus para cadastro de viagens, relatórios e perfil de usuário.
publish_to: 'none' # não publicar automaticamente

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Banco de dados SQLite
  sqflite: ^2.3.0
  path: ^1.8.3

  # Ícones e Material Design
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
